package com.parque_industrial.entities;

public enum CategoriaInventario {
    MAQUINARIA_PESADA,
    HERRAMIENTAS_MANUALES,
    EQUIPO_MEDICION,
    VEHICULOS_UTILITARIOS,
    MOBILIARIO_OFICINA,
    EQUIPO_INFORMATICO,
    DISPOSITIVOS_RED,
    SEGURIDAD_VIGILANCIA,
    PREVENCION_INCENDIOS,
    ILUMINACION_ELECTRICIDAD,
    REPUESTOS_INSUMOS,
    MATERIAL_CONSTRUCCION,
    LIMPIEZA_MANTENIMIENTO,
    PAPELERIA_ESCRITORIO,
    EQUIPO_PROTECCION_PERSONAL,
    OTROS
}