spring.application.name=parque-industrial
# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://viaduct.proxy.rlwy.net:20719/railway
spring.datasource.username=root
spring.datasource.password=jsZvFkoiyODiNzPpfuJHecBisDjIQRaf
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
# esto me lo recomendo la ia para evitar problemas de conexiones, pero no se si es necesario o no, lo dejo por si acaso